### ISSUE TITLE
QueryError

### ISSUE THREAD

**Issue by Caleculus** [vtex-soft/getmref#2]
Maybe I am wrong, but it looks like Mref has changed its address or appearance, so, for each entry GetMRef returns  Queryerror.

And, I will take this opportunity to thank you for this very useful program

**Comment by Caleculus** [comment]
[ns16284.getmref.log](https://github.com/user-attachments/files/17264282/ns16284.getmref.log)

And this is error file:
2024-10-05 00:31:59,301 ERROR >> Query FAILED!
Traceback (most recent call last):
  File "getmref.py", line 1014, in _send_query
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 473, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 403: Forbidden

**Comment by LolitaZT** [comment]
Hello,
Thank You for Your kind words.
Please update the program from this repository and try to use it again.
If the problem persists, reopen this issue.

**Comment by Caleculus** [comment]
Thank you. It works. I moved my staff to the new folder, kept the old one (do not know why) and forget to change global path variable. Now it works.
